In [1]:
import numpy as np

https://www.youtube.com/watch?v=arxmRnAdLy4&t=0s

### Exercises

The TPM of the Markovchain with three states 1,2,3 is 

$$\begin{bmatrix} 0.1 & 0.5 & 0.4 \\ 0.6 & 0.2 & 0.2 \\ 0.3 & 0.4 & 0.3 \end{bmatrix}$$

And the initial probability is (0.7,0.2,0.1)

calculate 

(i) P(X<sub>2</sub>  = 1)

In [ ]:
#The TPM of the Markovchain with three states 1,2,3 is 

In [4]:
tpm_list=[0.1,0.5,0.4,0.6,0.2,0.2,0.3,0.4,0.3]

In [2]:
np.arange(2,11)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
TPM=np.array(tpm_list).reshape(3,3)

In [11]:
TPM

array([[0.1, 0.5, 0.4],
       [0.6, 0.2, 0.2],
       [0.3, 0.4, 0.3]])

P(X<sub>2</sub>  = 1)=q<sub>2</sub>=q<sub>0</sub>P<sup>2</sup>

In [18]:
#initial probabilitie are given
q0=[0.7,0.2,0.1]
print(f'answer is {np.matmul(q0,np.matmul(TPM,TPM))[0]}')

answer is 0.38499999999999995


In [14]:
np.matmul(TPM,TPM)

array([[0.43, 0.31, 0.26],
       [0.24, 0.42, 0.34],
       [0.36, 0.35, 0.29]])

In [15]:
np.matmul(q0,np.matmul(TPM,TPM))

array([0.385, 0.336, 0.279])